/// Example: general-purpose Gzip compression on the Internet Computer.
///
/// Demonstrates how to compress and decompress arbitrary byte data safely
/// within the ICP instruction-limit by splitting work across multiple messages
/// via a self-call pattern.
///
/// Usage:
///   1. Call `generate_data(size_mb)` to fill the canister with pseudo-random data.
///   2. Call `compress_data()` to compress it (spreads work over several ICP messages).
///   3. Call `decompress_data()` to decompress and retrieve the bytes.
///   4. Compare with `get_generated_data()` to verify the round-trip.
import Array "mo:core/Array";
import List "mo:core/List";
import Nat "mo:core/Nat";
import Nat8 "mo:core/Nat8";
import Nat64 "mo:core/Nat64";
import Principal "mo:core/Principal";
import Random "mo:core/Random";
import Runtime "mo:core/Runtime";
import Gzip "../src/Gzip/lib";

shared ({ caller = _owner }) persistent actor class Compression() = self {

  // ── Constants ─────────────────────────────────────────────────────────────

  transient let MB = 1_024 * 1_024;

  transient let PAGE_SIZE : Nat = 2 * MB - 512;

  // ── Stable state ──────────────────────────────────────────────────────────

  var _data : ?[Nat8] = null;
  var _compressed : ?Gzip.EncodedResponse = null;
  var _decompressed : ?[Nat8] = null;

  // ── Transient state ───────────────────────────────────────────────────────

  transient let gzip_encoder = Gzip.EncoderBuilder().build();

  /// Bytes per self-call — derived from the encoder so both stay in sync.
  transient let ENCODE_CHUNK_SIZE : Nat = gzip_encoder.outputChunkSize();
  transient let gzip_decoder = Gzip.Decoder();

  /// Compressed chunks to decompress per self-call.
  /// At ~8.6B instructions per 6 MiB chunk, 3 chunks ≈ 25.8B — safely under the 40B limit.
  transient let DECODE_BATCH_SIZE : Nat = 3;

  /// Accumulates decompressed bytes across `_decompressBatch` self-calls.
  /// Cleared at the start of each `decompressData()` invocation.
  transient var _decompress_buf = List.empty<Nat8>();

  // ── Helpers ───────────────────────────────────────────────────────────────

  /// Split `data` into fixed-size chunks of at most `size` bytes.
  func chunks(data : [Nat8], size : Nat) : [[Nat8]] {
    let n = data.size();
    if (n == 0 or size == 0) return [data];
    let count = n / size + (if (n % size != 0) 1 else 0);
    Array.tabulate<[Nat8]>(
      count,
      func(i) {
        let lo = i * size;
        let hi = Nat.min(lo + size, n);
        Array.tabulate<Nat8>(hi - lo, func(j) { data[lo + j] });
      },
    );
  };

  func canisterId() : Principal { Principal.fromActor(self) };

  func getData() : [Nat8] {
    switch (_data) { case (?d) d; case null [] };
  };

  /// Return up to PAGE_SIZE bytes at index `page` (2 MiB pages, 0-indexed).
  /// Returns [] when `page` is past the end of `data`.
  func pageOf(data : [Nat8], page : Nat) : [Nat8] {
    let lo = page * PAGE_SIZE;
    let n = data.size();
    if (lo >= n) return [];
    let hi = Nat.min(lo + PAGE_SIZE, n);
    Array.tabulate<Nat8>(hi - lo, func(i) { data[lo + i] });
  };

  // ── Data generation ───────────────────────────────────────────────────────

  /// Fill the canister with `n_bytes` of structured test data split into thirds:
  ///   - first third:  constant byte (0xAA) — tests run-length compressibility
  ///   - middle third: pseudo-random bytes  — tests incompressible data
  ///   - last third:   sequential 0–255 loop — tests pattern compressibility
  public func generateBytes(n_bytes : Nat) : async () {
    let rng = Random.seed(42 : Nat64);
    let third = n_bytes / 3;
    _data := ?Array.tabulate<Nat8>(
      n_bytes,
      func(i) {
        if (i < third) {
          0xAA;
        } else if (i < 2 * third) {
          rng.nat8();
        } else {
          Nat8.fromNat(i % 256);
        };
      },
    );
  };

  /// Return a 2 MiB page of the raw generated bytes (0-indexed).
  /// Returns [] when `page` is past the end of the data.
  public query func getGeneratedData(page : Nat) : async [Nat8] {
    pageOf(getData(), page);
  };

  /// Return a 2 MiB page of the compressed output bytes (0-indexed).
  /// Returns [] when `page` is past the end of the compressed data.
  public query func getCompressedData(page : Nat) : async [Nat8] {
    let ?compressed = _compressed else return [];
    let bytes = switch (compressed) {
      case (#single data) data;
      case (#chunked chunks) Array.flatten<Nat8>(chunks);
    };
    pageOf(bytes, page);
  };

  // ── Compression ───────────────────────────────────────────────────────────

  /// Internal: encode one chunk.
  /// Guarded so only this canister may call it — each await gives the caller
  /// a fresh ICP instruction budget.
  public shared ({ caller }) func _compressChunk(chunk : [Nat8]) : async () {
    assert caller == canisterId();
    gzip_encoder.encode(chunk);
  };

  /// Internal: flush the final DEFLATE block, build output chunks, and persist the result.
  /// Isolated in a self-call so its instruction cost (proportional to total compressed size)
  /// gets a fresh budget, independent of the preceding encode calls.
  public shared ({ caller }) func _finishCompression() : async () {
    assert caller == canisterId();
    _compressed := ?gzip_encoder.finish();
  };

  /// Compress all stored data and persist the result.
  /// For data < ENCODE_CHUNK_SIZE, encodes in a single message then finalizes via self-call.
  /// For larger data, spreads encode work across ICP messages via self-calls.
  public func compressData() : async () {
    gzip_encoder.clear();
    let data = getData();

    if (data.size() < ENCODE_CHUNK_SIZE) {
      gzip_encoder.encode(data);
      _compressed := ?gzip_encoder.finish();
    } else {
      for (chunk in chunks(data, ENCODE_CHUNK_SIZE).vals()) {
        await _compressChunk(chunk);
      };
      await _finishCompression();
    };
  };

  // ── Decompression ─────────────────────────────────────────────────────────

  /// Internal: decompress a batch of compressed chunks (each a complete gzip stream) and
  /// append results to `_decompress_buf`. Batching up to DECODE_BATCH_SIZE chunks per
  /// self-call reduces inter-message round-trips while staying within the 40B limit.
  /// Guarded so only this canister may call it — each await gives a fresh instruction budget.
  public shared ({ caller }) func _decompressBatch(batch : [[Nat8]]) : async () {
    assert caller == canisterId();
    for (chunk in batch.vals()) {
      switch (gzip_decoder.decode(chunk)) {
        case (#err(msg)) Runtime.trap("_decompressBatch decode: " # msg);
        case (#ok(_)) {};
      };
      switch (gzip_decoder.finish()) {
        case (#err(msg)) Runtime.trap("_decompressBatch finish: " # msg);
        case (#ok(result)) List.addAll(_decompress_buf, result.bytes.vals());
      };
    };
  };

  /// Decompress the stored compressed data and cache the result in _decompressed.
  /// For `#single` output: decode + finish inline (≤ 1 chunk, always fits in one message).
  /// For `#chunked` output: self-calls process DECODE_BATCH_SIZE chunks each, each with a
  /// fresh instruction budget. Results accumulate in `_decompress_buf` and are converted
  /// to `[Nat8]` in a single O(N) pass via `List.toArray` after all batches complete.
  public func decompressData() : async () {
    gzip_decoder.clear();
    let ?compressed = _compressed else return;

    switch (compressed) {
      case (#single data) {
        switch (gzip_decoder.decode(data)) {
          case (#err(msg)) Runtime.trap("decompressData decode: " # msg);
          case (#ok(_)) {};
        };
        switch (gzip_decoder.finish()) {
          case (#err(msg)) Runtime.trap("decompressData finish: " # msg);
          case (#ok(result)) _decompressed := ?result.bytes;
        };
      };
      case (#chunked cs) {
        List.clear(_decompress_buf);
        let n = cs.size();
        var i = 0;
        while (i < n) {
          let hi = Nat.min(i + DECODE_BATCH_SIZE, n);
          let batch = Array.tabulate<[Nat8]>(hi - i, func(j) { cs[i + j] });
          await _decompressBatch(batch);
          i := hi;
        };
        _decompressed := ?List.toArray(_decompress_buf);
      };
    };
  };

  /// Return a 2 MiB page of the decompressed bytes (0-indexed).
  /// Returns [] when `page` is past the end or decompressData() has not been called.
  public query func getDecompressedData(page : Nat) : async [Nat8] {
    let ?d = _decompressed else return [];
    pageOf(d, page);
  };

};
