/// Example: general-purpose Gzip compression on the Internet Computer.
///
/// Demonstrates how to compress and decompress arbitrary byte data safely
/// within the ICP instruction-limit by splitting work across multiple messages
/// via a self-call pattern.
///
/// Usage:
///   1. Call `generate_data(size_mb)` to fill the canister with pseudo-random data.
///   2. Call `compress_data()` to compress it (spreads work over several ICP messages).
///   3. Call `decompress_data()` to decompress and retrieve the bytes.
///   4. Compare with `get_generated_data()` to verify the round-trip.
import Array "mo:core/Array";
import Nat "mo:core/Nat";
import Nat64 "mo:core/Nat64";
import Principal "mo:core/Principal";
import Random "mo:core/Random";
import Runtime "mo:core/Runtime";
import Gzip "../src/Gzip/lib";

shared ({ caller = _owner }) persistent actor class Compression() = self {

  // ── Constants ─────────────────────────────────────────────────────────────

  transient let MB = 1_024 * 1_024;
  transient let BLOCK_SIZE = 1 * MB;
  transient let PAGE_SIZE = 2 * MB;

  // ── Stable state ──────────────────────────────────────────────────────────

  var _data : ?[Nat8] = null;
  var _compressed : ?Gzip.EncodedResponse = null;
  var _decompressed : ?[Nat8] = null;

  // ── Transient state ───────────────────────────────────────────────────────

  transient let gzip_encoder = Gzip.EncoderBuilder().blockSize(BLOCK_SIZE).build();
  transient let gzip_decoder = Gzip.Decoder();

  // ── Helpers ───────────────────────────────────────────────────────────────

  /// Split `data` into fixed-size chunks of at most `size` bytes.
  func chunks(data : [Nat8], size : Nat) : [[Nat8]] {
    let n = data.size();
    if (n == 0 or size == 0) return [data];
    let count = n / size + (if (n % size != 0) 1 else 0);
    Array.tabulate<[Nat8]>(
      count,
      func(i) {
        let lo = i * size;
        let hi = Nat.min(lo + size, n);
        Array.tabulate<Nat8>(hi - lo, func(j) { data[lo + j] });
      },
    );
  };

  func canister_id() : Principal { Principal.fromActor(self) };

  func get_data() : [Nat8] {
    switch (_data) { case (?d) d; case null [] };
  };

  /// Return up to PAGE_SIZE bytes at index `page` (2 MiB pages, 0-indexed).
  /// Returns [] when `page` is past the end of `data`.
  func page_of(data : [Nat8], page : Nat) : [Nat8] {
    let lo = page * PAGE_SIZE;
    let n = data.size();
    if (lo >= n) return [];
    let hi = Nat.min(lo + PAGE_SIZE, n);
    Array.tabulate<Nat8>(hi - lo, func(i) { data[lo + i] });
  };

  // ── Data generation ───────────────────────────────────────────────────────

  /// Fill the canister with `size_mb` MB of pseudo-random bytes.
  /// Use size_mb=1 for correctness tests, size_mb=10 for perf scripts.
  public func generate_data(size_mb : Nat) : async () {
    let rng = Random.seed(42 : Nat64);
    _data := ?Array.tabulate<Nat8>(size_mb * MB, func(_) { rng.nat8() });
  };

  /// Return a 2 MiB page of the raw generated bytes (0-indexed).
  /// Returns [] when `page` is past the end of the data.
  public query func get_generated_data(page : Nat) : async [Nat8] {
    page_of(get_data(), page);
  };

  /// Return a 2 MiB page of the compressed output bytes (0-indexed).
  /// Returns [] when `page` is past the end of the compressed data.
  public query func get_compressed_data(page : Nat) : async [Nat8] {
    let ?compressed = _compressed else return [];
    page_of(Array.flatten<Nat8>(compressed.chunks), page);
  };

  // ── Compression ───────────────────────────────────────────────────────────

  /// Internal: encode one chunk.
  /// Guarded so only this canister may call it — each await gives the caller
  /// a fresh ICP instruction budget.
  public shared ({ caller }) func _compress_chunk(chunk : [Nat8]) : async () {
    assert caller == canister_id();
    gzip_encoder.encode(chunk);
  };

  /// Compress all stored data in BLOCK_SIZE chunks and persist the result.
  /// Spreads work across ICP messages via self-calls.
  public func compress_data() : async () {
    for (chunk in chunks(get_data(), BLOCK_SIZE).vals()) {
      await _compress_chunk(chunk);
    };
    _compressed := ?gzip_encoder.finish();
  };

  // ── Decompression ─────────────────────────────────────────────────────────

  /// Internal: accumulate one compressed chunk.
  /// Guarded so only this canister may call it.
  public shared ({ caller }) func _decode_chunk(chunk : [Nat8]) : async () {
    assert caller == canister_id();
    switch (gzip_decoder.decode(chunk)) {
      case (#err(msg)) Runtime.trap("_decode_chunk: " # msg);
      case (#ok(_)) {};
    };
  };

  /// Decompress the stored compressed data and cache the result in _decompressed.
  public func decompress_data() : async () {
    let ?compressed = _compressed else return;
    for (chunk in compressed.chunks.vals()) {
      await _decode_chunk(chunk);
    };
    switch (gzip_decoder.finish()) {
      case (#err(msg)) Runtime.trap("decompress_data: " # msg);
      case (#ok(result)) _decompressed := ?result.bytes;
    };
  };

  /// Return a 2 MiB page of the decompressed bytes (0-indexed).
  /// Returns [] when `page` is past the end or decompress_data() has not been called.
  public query func get_decompressed_data(page : Nat) : async [Nat8] {
    let ?d = _decompressed else return [];
    page_of(d, page);
  };

};
